version: 0.2

phases:
  install: 
    runtime-versions:
      standard:2.0
      
    commands:
      - echo "geez install"
      - apt-get update -y 
      
  pre_build:
    commands:
      -echo "geez prebuild"
  
  build:
    commands:
      -echo "geez build"
  
  post_build:
    commands:
      -echo "geez post_build"
