pipeline {
    agent any
    environment {
        JENKINS_ANACONDA_DIR='/var/lib/jenkins/anaconda3'
        JENKINS_PYTHON_ENV='pr_env'
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    . $JENKINS_ANACONDA_DIR/etc/profile.d/conda.sh
                    if [ ! -d "$JENKINS_ANACONDA_DIR/envs/$JENKINS_PYTHON_ENV" ]; then
                        conda create --name $JENKINS_PYTHON_ENV python=3.6 -y
                    fi
                    conda activate $JENKINS_PYTHON_ENV
                    pip install pytest numpy nibabel pydicom twine ipython ipykernel
                    conda install tensorflow=2.0.0
                    pip install -e .
                    pip freeze | tee requirement.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    . $JENKINS_ANACONDA_DIR/etc/profile.d/conda.sh
                    conda activate $JENKINS_PYTHON_ENV
                    python3 -m pytest
                '''
            }
        }
    }
}