pipeline{
    agent {label 'ec2-fleet'}
    stages{
        stage('Test'){
            steps{
                sh '''
                echo hello world
                '''
            }
        }
    }
}