# Copyright 2026 The FastEstimator Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
from typing import Any, Dict, Iterable, List, Tuple, Union

import numpy as np
from scipy.ndimage import gaussian_filter, map_coordinates

from fastestimator.op.numpyop.numpyop import NumpyOp
from fastestimator.util.traceability_util import traceable


@traceable()
class ElasticTransform3D(NumpyOp):
    """Apply elastic deformation to a 3D volume.

    This op expects input data with shape (D, H, W) or (D, H, W, C). Elastic deformations are one of the most
    important augmentations for medical image segmentation, as they simulate realistic anatomical variations.
    The same deformation field is applied to all inputs (image and mask together).

    The deformation is generated by creating random displacement fields and smoothing them with a Gaussian filter.
    Larger sigma values produce smoother (more global) deformations, while larger alpha values produce stronger
    deformations.

    Reference: Simard et al., "Best Practices for Convolutional Neural Networks Applied to Visual Document Analysis",
    ICDAR 2003.

    Args:
        inputs: Key(s) of 3D volumes to be deformed.
        outputs: Key(s) into which to write the deformed volumes.
        mode: What mode(s) to execute this Op in. For example, "train", "eval", "test", or "infer". To execute
            regardless of mode, pass None. To execute in all modes except for a particular one, you can pass an argument
            like "!infer" or "!train".
        ds_id: What dataset id(s) to execute this Op in. To execute regardless of ds_id, pass None. To execute in all
            ds_ids except for a particular one, you can pass an argument like "!ds1".
        alpha: Scaling factor for the displacement field. Controls the intensity of the deformation. Typical values
            are in the range [100, 1000] for medical volumes.
        sigma: Standard deviation of the Gaussian filter applied to smooth the displacement field. Controls the
            smoothness of the deformation. Typical values are in the range [10, 30].
        order: Interpolation order (0=nearest, 1=linear, 3=cubic). Use 0 for label masks.
        fill_value: Value used for points outside the boundaries of the input.
        label_keys: Key(s) that should be treated as label/mask data (using nearest-neighbor interpolation).

    Volume types:
        float32, float64, int16, int32, uint8
    """
    def __init__(self,
                 inputs: Union[str, Iterable[str]],
                 outputs: Union[str, Iterable[str]],
                 alpha: float = 200.0,
                 sigma: float = 20.0,
                 order: int = 1,
                 fill_value: float = 0.0,
                 label_keys: Union[None, str, Iterable[str]] = None,
                 mode: Union[None, str, Iterable[str]] = None,
                 ds_id: Union[None, str, Iterable[str]] = None):
        super().__init__(inputs=inputs, outputs=outputs, mode=mode, ds_id=ds_id)
        self.alpha = alpha
        self.sigma = sigma
        self.order = order
        self.fill_value = fill_value
        self.label_keys = set() if label_keys is None else (
            {label_keys} if isinstance(label_keys, str) else set(label_keys))
        self.in_list, self.out_list = True, True

    def forward(self, data: List[np.ndarray], state: Dict[str, Any]) -> List[np.ndarray]:
        shape = data[0].shape[:3]
        coords = self._generate_displacement_field(shape)
        results = []
        for i, elem in enumerate(data):
            key = self.inputs[i] if i < len(self.inputs) else None
            is_label = key in self.label_keys
            results.append(self._apply(elem, coords, is_label))
        return results

    def _generate_displacement_field(self, shape: Tuple[int, ...]) -> List[np.ndarray]:
        """Generate a smooth random displacement field for the given volume shape."""
        # Generate random displacements and smooth them
        dz = gaussian_filter(np.random.randn(*shape) * self.alpha, self.sigma)
        dy = gaussian_filter(np.random.randn(*shape) * self.alpha, self.sigma)
        dx = gaussian_filter(np.random.randn(*shape) * self.alpha, self.sigma)

        # Create coordinate grids
        z, y, x = np.meshgrid(np.arange(shape[0]), np.arange(shape[1]), np.arange(shape[2]), indexing='ij')
        coords = [
            np.clip(z + dz, 0, shape[0] - 1),
            np.clip(y + dy, 0, shape[1] - 1),
            np.clip(x + dx, 0, shape[2] - 1),
        ]
        return coords

    def _apply(self, data: np.ndarray, coords: List[np.ndarray], is_label: bool) -> np.ndarray:
        order = 0 if is_label else self.order
        if data.ndim == 3:
            result = map_coordinates(data, coords, order=order, mode='constant', cval=self.fill_value)
        else:
            # (D, H, W, C): apply deformation to each channel independently
            channels = []
            for c in range(data.shape[3]):
                ch = map_coordinates(data[..., c], coords, order=order, mode='constant', cval=self.fill_value)
                channels.append(ch)
            result = np.stack(channels, axis=-1)
        return result.astype(data.dtype)
