pipeline {
    agent {label 'master'}
    environment {
        JENKINS_ANACONDA_DIR='/var/jenkins_home/anaconda3'
        JENKINS_PYTHON_ENV='pr_env_conda'
    }
    stages {
        stage('Build') {
            steps {
                sh '''#!/bin/bash
                    set -e
                    source ~/.bashrc
                    . $JENKINS_ANACONDA_DIR/etc/profile.d/conda.sh
                    if [ ! -d "$JENKINS_ANACONDA_DIR/envs/$JENKINS_PYTHON_ENV" ]; then
                        conda create --name $JENKINS_PYTHON_ENV python=3.6 -y
                    fi
                    conda activate $JENKINS_PYTHON_ENV
                    pip install --no-cache-dir -e .
                    pip install --no-cache-dir coverage
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''#!/bin/bash
                    set -e
                    . $JENKINS_ANACONDA_DIR/etc/profile.d/conda.sh
                    conda activate $JENKINS_PYTHON_ENV
                    python3 test/run_pr_test.py
                '''
            }
        }
    }
}