def IMAGE_TAG="$BUILD_TAG".toLowerCase()

pipeline {
    agent {label 'master'}
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    environment {
        IMAGE_TAG="$IMAGE_TAG"
    }
    stages {
        stage('PR-test') {
            steps {
                script {
                    def customImage = docker.build("$IMAGE_TAG", "--no-cache - < docker/nightly/Dockerfile.cpu")
                    try {
                        customImage.inside('-u root') {
                            sh 'pip install --no-cache-dir .'
                            sh 'python test/run_pr_test.py'
                        }
                    }
                    finally {
                        sh 'docker rmi "$IMAGE_TAG"'
                    }
                }
            }
        }
    }
}